# Site settings
title: Florida
client:
  name: Virgin Holidays
  link: https://www.virginholidays.co.uk/destinations/florida-holidays
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Head for the Sunshine State and immerse yourself in an outdoor wonderland that harbours some of the finest adventures in America.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/florida" # the subpath of your site, e.g. /blog/
img:     "/florida/_assets/img"
css:     "/florida/_assets/css"
js:      "/florida/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed